version: "3.8"

services:
  dtl-mainnet:
    image: ericlee42/metis-dtl:20211129
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
        # used for setting the address manager address
        URL: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/addresses.json
        # replace YOUR_INFURA_TOKEN to your mainnet token
        DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: https://mainnet.infura.io/v3/YOUR_INFURA_TOKEN
        # Metis endpoint, see https://docs.metis.io/building-on-metis/connection-detailsee 
        DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: "https://andromeda.metis.io/?owner=1088"
        DATA_TRANSPORT_LAYER__SYNC_FROM_L1: "true"
        DATA_TRANSPORT_LAYER__SYNC_FROM_L2: "false"
        DATA_TRANSPORT_LAYER__L2_CHAIN_ID: "1088"
        # Path to the database for this service.
        DATA_TRANSPORT_LAYER__DB_PATH: /data/db
        DATA_TRANSPORT_LAYER__SERVER_PORT: "7878"
        DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: "1000"
        DATA_TRANSPORT_LAYER__CONFIRMATIONS: "12"
        # Period of time between execution loops.
        DATA_TRANSPORT_LAYER__POLLING_INTERVAL: "100"
        # Logs to sync per polling interval.
        DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: "2000"
        DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: "true"
        DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: "0.0.0.0"
    ports:
      - ${DTL_PORT:-7878}:7878
    volumes:
      - /data/metis/mainnet/dtl:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  dtl-expose:
    image: ericlee42/metis-dtl-expose:latest
    restart: unless-stopped
    ports:
      - 8080:8080

  l2geth-mainnet:
    image: ericlee42/metis-l2geth:20211124
    entrypoint: sh ./geth.sh
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
        # replace YOUR_INFURA_TOKEN to your mainnet token
        ETH1_HTTP: https://mainnet.infura.io/v3/YOUR_INFURA_TOKEN
        ROLLUP_STATE_DUMP_PATH: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/state-dump.latest.json
        ROLLUP_CLIENT_HTTP: http://dtl-mainnet:7878
        ROLLUP_BACKEND: "l1"
        CHAIN_ID: 1088
        NETWORK_ID: 1088
        ETH1_CTC_DEPLOYMENT_HEIGHT: 8
        RETRIES: 60
        ROLLUP_VERIFIER_ENABLE: "true"
        BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
        BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
        ETH1_SYNC_SERVICE_ENABLE: "true"
        ETH1_CONFIRMATION_DEPTH: 0
        ROLLUP_POLL_INTERVAL_FLAG: "500ms"
        ROLLUP_ENABLE_L2_GAS_POLLING: "true"
        RPC_ENABLE: "true"
        RPC_ADDR: "0.0.0.0"
        RPC_PORT: "8545"
        RPC_API: eth,net,rollup,web3,admin,txpool,debug
        RPC_CORS_DOMAIN: "*"
        RPC_VHOSTS: "*"
        WS: "true"
        WS_ADDR: "0.0.0.0"
        WS_PORT: "8546"
        WS_API: "eth,net,rollup,web3"
        WS_ORIGINS: "*"
        DATADIR: "/root/.ethereum"
        GASPRICE: 0
        GCMODE: "archive"
        IPC_DISABLE: "true"
        NO_USB: "true"
        NO_DISCOVER: "true"
        TARGET_GAS_LIMIT: 1100000000
        USING_OVM: "true"
    ports:
      - ${VERIFIER_HTTP_PORT:-8549}:8545
      - ${VERIFIER_WS_PORT:-8550}:8546
    volumes:
      - /data/metis/mainnet/l2geth:/root/.ethereum
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
