version: "3.8"

services:
  dtl-mainnet:
    image: metisdao/mvm-andromeda:verifier-dtl
    container_name: metis-dtl
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: ${ETHEREUM_RPC_ENDPOINT:?Set Ethereum rpc endpint first}
    env_file: [ "dtl.env" ]
    ports:
      - ${DTL_PORT:-7878}:7878
    volumes:
      - ${METIS_VERIFIER_DATADIR:-/data/metis/mainnet}/dtl:/data
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  dtl-expose:
    image: ericlee42/metis-dtl-expose:latest
    container_name: metis-expose
    restart: unless-stopped
    ports:
      - 8080:8080

  l2geth-mainnet:
    image: metisdao/mvm-andromeda:verifier-l2geth
    container_name: metis-l2geth
    restart: unless-stopped
    stop_grace_period: 2m
    env_file: [ "l2geth.env" ]
    environment:
      ETH1_HTTP: ${ETHEREUM_RPC_ENDPOINT:?Set Ethereum rpc endpint first}
    ports:
      - ${VERIFIER_HTTP_PORT:-8549}:8545
      - ${VERIFIER_WS_PORT:-8550}:8546
    volumes:
      - ${METIS_VERIFIER_DATADIR:-/data/metis/mainnet}/l2geth:/root/.ethereum
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
